[package]
name = "ftables_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
rlrl = { git = "https://www.github.com/finleyowen/rlrl.git", version = "0.1.0" }
serde_json = "1.0.149"
